# -*- coding: utf-8 -*-
"""q2 codinglab4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r8TKtEfm7-sfXxvj3TotMj0sL1-Zoytx
"""

#X = np.random.rand(1000) * 100
#Y = np.random.normal(50, 10, 1000)
#     1a) x is an array that has 1000 evenly distributed numbers between 1 and 100
#     1b) y is an array with 1000 numbers, a mean of 50 and a std deviation of 10

#2)
import matplotlib.pyplot as plt
import numpy as np

X = np.random.rand(1000) * 100
Y = np.random.normal(50, 10, 1000)

Xm = X.mean()
Xs = X.std()

Ym = Y.mean()
Ys = Y.std()

print("the mean of X is " + str(Xm))
print("the std deviation of X is " + str(Xs))
print("the mean of Y is " + str(Ym))
print("the std deviation of Y is " + str(Ys))

#3)
import matplotlib.pyplot as plt
import numpy as np

X = np.random.rand(1000) * 100
Y = np.random.normal(50, 10, 1000)

plt.figure("Q2")
plt.hist(X, bins = 20, edgecolor ='purple', alpha = 0.50, label = 'X')
plt.hist(Y, bins = 20, edgecolor='violet', alpha = 0.50, label = 'Y')
plt.legend()
plt.show()

#4)

#4a) histogram X is more uniform. like no obvious trend line is apparent
#4b) histogram Y is more like an exponential graph aka "bell-shaped"