# -*- coding: utf-8 -*-
"""question1 codinglab4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ToCvJVFpdLeUproW87GNbEtSFYKttfk4
"""

import matplotlib.pyplot as plt
import numpy as np
size = 100

x1 = np.linspace(-3*np.pi+(np.pi / 2), 3*np.pi+(np.pi / 2), size)
x2 = np.linspace(-3*np.pi, 3*np.pi, size)

y1 = 2 * np.sin(x1)
y2 = 2 * np.cos(x2)


plt.figure("Q1")

def plot(x, y, label, marker="-"):
    
    i = 1
    
    while i < len(x):
        
        ylst = [y[i-1]]
        xlst = [x[i-1]]
        
        if y[i] > y[i-1]:
            
            while i < len(y) and y[i] > y[i-1]:
                ylst.append(y[i])
                xlst.append(x[i])
                i += 1
            
            color = "green"
        
        else:
            
            while i < len(y) and y[i] <= y[i-1]:
                ylst.append(y[i])
                xlst.append(x[i])
                i += 1
            
            color = "red"
        
        if i == len(x-1):
            plt.plot(xlst, ylst, marker, color = color, label = label)
        else:
            plt.plot(xlst, ylst, marker, color = color)

plot(x1, y1, label="2sin(x)")
plot(x2, y2, label="2cos(x)", marker="--")


plt.xlabel('X', fontsize = 15)
plt.ylabel('Y', fontsize = 15)

plt.ylim(-4, 4)

plt.grid(color = "blue", alpha = 0.2)

plt.legend()